version: "2"

services:
  mongodb:
    image: "mongo"
    ports:
      - 27017:27017
  app:
    tty: true
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/partners-location
    build: .
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules
